name: "My workflow"
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
          distribution: 'corretto'
          java-version: '8'
    - name: Build with Maven
      run: mvn package 
